### ISSUE TITLE
Bug: Hub Network Name in Complete design - inherits the "root-id" from the YAML

### ISSUE THREAD

**Issue by faolain-git** [Azure/Azure-Landing-Zones#2452]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Infrastructure as Code Type? (Required)

terraform

### PowerShell Module Version (Optional)

7.2

### Bootstrap Module Version (Optional)

4.1.4

### Starter Module? (Required)

terraform - complete

### Starter Module Version (Optional)

4.5.0

### Debug Output/Panic Output (Optional)

```shell

```

### Expected Behaviour (Required)

When editing the "complete" configuration, the usage of the name element for the Hub Virtual Network appears to be overlooked

```
  configure_connectivity_resources:
    settings:
      hub_networks:
        - config:
            address_space: ["172.20.2.0/24"]
            location: ${starter_location}
            name: vnet-customhubname-region-01
            resource_group_name: rg-customrgname-region-01
```

### Actual Behaviour (Required)

the hub virtual network is created with the Root ID element prepended, "mg-root" for example, and the remaining naming convention "-hub-northeurope" for example. 

Other configurations, config-hub-and-spoke-vnet-multi-region.yaml for example, use a different set of elements. Is one preferened to the other?
