### ISSUE TITLE
Bug: Approvers are not added to the alz-mgmt-approvers team

### ISSUE THREAD

**Issue by autocloudarc** [Azure/Azure-Landing-Zones#2457]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Infrastructure as Code Type? (Required)

terraform

### PowerShell Module Version (Optional)

4.1.1

### Bootstrap Module Version (Optional)

4.1.4

### Starter Module? (Required)

terraform - complete

### Input arguments of the ALZ-PowerShell-Module (Optional)

Deploy-Accelerator -iac_type "terraform" -inputs "C:\accelerator\config\ghb-inputs.yaml" -auto_approve -output C:\accelerator\output -Verbose

### Debug Output/Panic Output (Optional)

```shell

```

### Expected Behaviour (Required)

By virtue of specifying an **apply_approvers** value as shown in the partial ghb-inputs.yaml file, (github-member@<domain>.com is just a placeholder for confidentiality) I expected that this member would be added to the **alz-mgmt-approvers** team.

```yaml
# Apply stage approvers to the action / pipeline, must be a list of SPNs separate by a comma (e.g. abcdef@microsoft.com,ghijklm@microsoft.com) using team "alz-mgmt-approvers"
apply_approvers: ["github-member@<domain>.com"]
# Create branch policies for the main branch
create_branch_policies: "true"
```

### Actual Behaviour (Required)

When I run the bootstrap command to stage the deployment, the **alz-mgmt-approvers**  team does not get populated with the specified approver from the input file.

I'm deploying to a GitHub Enterprise Cloud account (not EMU).

![Image](https://github.com/user-attachments/assets/0361ac52-f3d8-4419-97b9-94f5b7480179)

### Steps to Reproduce (Optional)

1. Follow the provided instructions [here:](https://github.com/Azure/ALZ-PowerShell-Module/wiki/%5BUser-Guide%5D-Quick-Start-Phase-2-GitHub#2222-github-with-terraform)
2. Run the command: Deploy-Accelerator -iac_type "terraform" -inputs "C:\accelerator\config\ghb-inputs.yaml" -auto_approve -output C:\accelerator\output -Verbose
3. Approve the plan to start the apply phase
4. Wait for the apply phase to complete
5. In the GitHub organization, check the membership of the **alz-mgmt-approvers**

### Important Factoids (Optional)

Note that branch policies do get created though, and the **Required reviewers** box is checked with the **alz-mgmt-approvers** team selected, but it's still an empty team. 

![Image](https://github.com/user-attachments/assets/e5840fa0-b55d-487b-ab1b-0e4c325437f4)

This is for the Azure Commercial Cloud.

As a workaround, I can still manually add members to the **alz-mgmt-approvers** team in the GitHub interface, but it does disrupt the automation flow. Thanks for reviewing. 

### References (Optional)

input-file-sample (https://raw.githubusercontent.com/wiki/Azure/ALZ-PowerShell-Module/examples/powershell-inputs/inputs-github-terraform-complete.yaml)
